//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Dat_HeroData.proto
// Note: requires additional types generated from: Dat_General.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAT_HeroData")]
  public partial class DAT_HeroData : global::ProtoBuf.IExtensible
  {
    public DAT_HeroData() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _lv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _experience;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"experience", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int experience
    {
      get { return _experience; }
      set { _experience = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _heroUId = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"heroUId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> heroUId
    {
      get { return _heroUId; }
    }
  
    private ProtoBuf.DAT_ElementType _elementType;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"elementType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.DAT_ElementType elementType
    {
      get { return _elementType; }
      set { _elementType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}