//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Dat_HeroData.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAT_HeroDataStatic")]
  public partial class DAT_HeroDataStatic : global::ProtoBuf.IExtensible
  {
    public DAT_HeroDataStatic() {}
    
    private string _heroId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _atk;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"atk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int atk
    {
      get { return _atk; }
      set { _atk = value; }
    }
    private int _def;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private int _speed;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _skill = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(15, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> skill
    {
      get { return _skill; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAT_HeroData")]
  public partial class DAT_HeroData : global::ProtoBuf.IExtensible
  {
    public DAT_HeroData() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _heroId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"heroId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string heroId
    {
      get { return _heroId; }
      set { _heroId = value; }
    }
    private int _lv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _experience;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"experience", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int experience
    {
      get { return _experience; }
      set { _experience = value; }
    }
    private int _atk;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"atk", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int atk
    {
      get { return _atk; }
      set { _atk = value; }
    }
    private int _def;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"def", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int def
    {
      get { return _def; }
      set { _def = value; }
    }
    private int _speed;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _skill = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(15, Name=@"skill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> skill
    {
      get { return _skill; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}