//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Dat_BattleData.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAT_HeroDataInBattle")]
  public partial class DAT_HeroDataInBattle : global::ProtoBuf.IExtensible
  {
    public DAT_HeroDataInBattle() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _physicalAttack;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"physicalAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int physicalAttack
    {
      get { return _physicalAttack; }
      set { _physicalAttack = value; }
    }
    private int _physicalDefence;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"physicalDefence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int physicalDefence
    {
      get { return _physicalDefence; }
      set { _physicalDefence = value; }
    }
    private int _magicalAttack;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"magicalAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int magicalAttack
    {
      get { return _magicalAttack; }
      set { _magicalAttack = value; }
    }
    private int _magicalDefence;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"magicalDefence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int magicalDefence
    {
      get { return _magicalDefence; }
      set { _magicalDefence = value; }
    }
    private int _absoluteAttack;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"absoluteAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int absoluteAttack
    {
      get { return _absoluteAttack; }
      set { _absoluteAttack = value; }
    }
    private float _speed;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"speed", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float speed
    {
      get { return _speed; }
      set { _speed = value; }
    }
    private int _move;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"move", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int move
    {
      get { return _move; }
      set { _move = value; }
    }
    private int _attackRange;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"attackRange", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int attackRange
    {
      get { return _attackRange; }
      set { _attackRange = value; }
    }
    private int _hp;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"hp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hp
    {
      get { return _hp; }
      set { _hp = value; }
    }
    private float _progress;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float progress
    {
      get { return _progress; }
      set { _progress = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _buffs = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(12, Name=@"buffs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> buffs
    {
      get { return _buffs; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAT_HeroBuff")]
  public partial class DAT_HeroBuff : global::ProtoBuf.IExtensible
  {
    public DAT_HeroBuff() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _iparas = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(4, Name=@"iparas", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> iparas
    {
      get { return _iparas; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _fparas = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(5, Name=@"fparas", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public global::System.Collections.Generic.List<float> fparas
    {
      get { return _fparas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}