//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Dat_UserData.proto
// Note: requires additional types generated from: Dat_General.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAT_UserData")]
  public partial class DAT_UserData : global::ProtoBuf.IExtensible
  {
    public DAT_UserData() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _nickname;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private int _lv;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lv
    {
      get { return _lv; }
      set { _lv = value; }
    }
    private int _experience;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"experience", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int experience
    {
      get { return _experience; }
      set { _experience = value; }
    }
    private string _roleId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private int _strength;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private int _magic;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"magic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int magic
    {
      get { return _magic; }
      set { _magic = value; }
    }
    private int _agility;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"agility", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int agility
    {
      get { return _agility; }
      set { _agility = value; }
    }
    private ProtoBuf.DAT_ElementProperty _elementProperty;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"elementProperty", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.DAT_ElementProperty elementProperty
    {
      get { return _elementProperty; }
      set { _elementProperty = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _heroes = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(10, Name=@"heroes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> heroes
    {
      get { return _heroes; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _teams = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(11, Name=@"teams", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> teams
    {
      get { return _teams; }
    }
  
    private int _gold;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"gold", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gold
    {
      get { return _gold; }
      set { _gold = value; }
    }
    private int _gem;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"gem", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gem
    {
      get { return _gem; }
      set { _gem = value; }
    }
    private ProtoBuf.DAT_ElementProperty _keys;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"keys", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.DAT_ElementProperty keys
    {
      get { return _keys; }
      set { _keys = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}