//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Dat_RoleData.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAT_RoleDataStatic")]
  public partial class DAT_RoleDataStatic : global::ProtoBuf.IExtensible
  {
    public DAT_RoleDataStatic() {}
    
    private string _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roleId
    {
      get { return _roleId; }
      set { _roleId = value; }
    }
    private int _strength;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"strength", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int strength
    {
      get { return _strength; }
      set { _strength = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _magic = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"magic", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> magic
    {
      get { return _magic; }
    }
  
    private int _agility;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"agility", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int agility
    {
      get { return _agility; }
      set { _agility = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}