//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Dat_CityData.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAT_CityDataStatic")]
  public partial class DAT_CityDataStatic : global::ProtoBuf.IExtensible
  {
    public DAT_CityDataStatic() {}
    
    private string _cityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cityId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string cityId
    {
      get { return _cityId; }
      set { _cityId = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _posx;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"posx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posx
    {
      get { return _posx; }
      set { _posx = value; }
    }
    private int _posy;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"posy", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int posy
    {
      get { return _posy; }
      set { _posy = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAT_CityData")]
  public partial class DAT_CityData : global::ProtoBuf.IExtensible
  {
    public DAT_CityData() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private ProtoBuf.DAT_CityDataStatic _dataStatic;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dataStatic", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.DAT_CityDataStatic dataStatic
    {
      get { return _dataStatic; }
      set { _dataStatic = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}