//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Dat_General.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAT_ElementProperty")]
  public partial class DAT_ElementProperty : global::ProtoBuf.IExtensible
  {
    public DAT_ElementProperty() {}
    
    private int _air;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"air", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int air
    {
      get { return _air; }
      set { _air = value; }
    }
    private int _water;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"water", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int water
    {
      get { return _water; }
      set { _water = value; }
    }
    private int _fire;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"fire", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fire
    {
      get { return _fire; }
      set { _fire = value; }
    }
    private int _earth;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"earth", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int earth
    {
      get { return _earth; }
      set { _earth = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DAT_ElementType")]
  public partial class DAT_ElementType : global::ProtoBuf.IExtensible
  {
    public DAT_ElementType() {}
    
    [global::ProtoBuf.ProtoContract(Name=@"ele")]
    public enum ele
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Air", Value=0)]
      Air = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Water", Value=1)]
      Water = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Fire", Value=2)]
      Fire = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Earth", Value=3)]
      Earth = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}