//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Msg_MatchOpponent.proto
// Note: requires additional types generated from: Dat_HeroData.proto
// Note: requires additional types generated from: Dat_UserData.proto
namespace ProtoBuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"C2S_MatchOpponent")]
  public partial class C2S_MatchOpponent : global::ProtoBuf.IExtensible
  {
    public C2S_MatchOpponent() {}
    
    private string _team;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"team", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string team
    {
      get { return _team; }
      set { _team = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"S2C_MatchOpponent")]
  public partial class S2C_MatchOpponent : global::ProtoBuf.IExtensible
  {
    public S2C_MatchOpponent() {}
    
    private int _ret;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ret
    {
      get { return _ret; }
      set { _ret = value; }
    }
    private string _battleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"battleId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string battleId
    {
      get { return _battleId; }
      set { _battleId = value; }
    }
    private ProtoBuf.DAT_UserData _opponent;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"opponent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ProtoBuf.DAT_UserData opponent
    {
      get { return _opponent; }
      set { _opponent = value; }
    }
    private string _opponentTeam;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"opponentTeam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string opponentTeam
    {
      get { return _opponentTeam; }
      set { _opponentTeam = value; }
    }
    private readonly global::System.Collections.Generic.List<ProtoBuf.DAT_HeroData> _opponentHeroes = new global::System.Collections.Generic.List<ProtoBuf.DAT_HeroData>();
    [global::ProtoBuf.ProtoMember(5, Name=@"opponentHeroes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ProtoBuf.DAT_HeroData> opponentHeroes
    {
      get { return _opponentHeroes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}